import { useState } from 'react';
import Head from 'next/head';

const Home = () => {
  const [showPopup, setShowPopup] = useState(false);

  const handleButtonClick = () => {
    setShowPopup(true);
  };

  const handleClosePopup = () => {
    setShowPopup(false);
  };

  return (
    <>
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative min-h-screen flex items-center justify-center bg-gray-100">
        <button
          onClick={handleButtonClick}
          className="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-700 transition"
        >
          Open Popup
        </button>

        {showPopup && (
          <>
            <div className="fixed inset-0 bg-black bg-opacity-50 backdrop-blur-sm z-10" onClick={handleClosePopup}></div>
            <div className="fixed inset-0 flex items-center justify-center z-20">
              <div className="bg-white p-6 rounded shadow-lg relative max-w-md mx-auto animate-fade-in">
                <button
                  onClick={handleClosePopup}
                  className="absolute top-2 right-2 text-gray-500 hover:text-gray-700"
                >
                  &times;
                </button>
                <h2 className="text-2xl mb-4">This is a popup</h2>
                <p className="mb-4">Some content here</p>
                <button
                  onClick={handleClosePopup}
                  className="bg-red-500 text-white py-2 px-4 rounded hover:bg-red-700 transition"
                >
                  Close
                </button>
              </div>
            </div>
          </>
        )}
      </div>
    </>
  );
};

export default Home;
